
/*
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 + Lamps contains names for all lamps.                                 +
 + Feel free to edit keys and values, but keep them unique.            +
 + Lamps structure is only used in configuration of both FlipperDriver +
 + and StateMachine.                                                   +
 + Use of refactoring tool recommended.                                +
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */

/**
 * Enum with lamp names.
 */
module.exports = {
    // Lamp matrix A
    START_BUTTON: 'StartButton',
    SHIELD_LOWER_RIGHT: 'ShieldLowerRight',
    SHIELD_LOWER_4: 'ShieldLower4',
    SHIELD_LOWER_3: 'ShieldLower3',
    SHIELD_LOWER_2: 'ShieldLower2',
    TICKETS_LOW: 'TicketsLow',
    COIN_DOOR_ILLUMINATION: 'CoinDoorIllumination',
    SHIELD_MIDDLE_RIGHT: 'ShieldMiddleRight',
    SHIELD_MIDDLE_3: 'ShieldMiddle3',
    SHIELD_MIDDLE_2: 'ShieldMiddle2',
    SHIELD_LOWER_LEFT: 'ShieldLowerLeft',
    SHIELD_UPPER_RIGHT: 'ShieldUpperRight',
    SHIELD_UPPER_MIDDLE: 'ShieldUpperMiddle',
    SHIELD_MIDDLE_LEFT: 'ShieldMiddleLeft',
    SHIELD_UPPER_LEFT: 'ShieldUpperLeft',
    LEFT_LOOP_RIGHT_LEG: 'LeftLoopRightLeg',
    LEFT_LOOP_RIGHT_FOOT: 'LeftLoopRightFoot',
    LEFT_LOOP_LEFT_FOOT: 'LeftLoopLeftFoot',
    LEFT_LOOP_LEFT_LEG: 'LeftLoopLeftLeg',
    JEDI_E: 'JediE',
    JEDI_J: 'JediJ',
    JEDI_I: 'JediI',
    JEDI_D: 'JediD',
    LEFT_LOOP_BODY_MIDDLE: 'LeftLoopBodyMiddle',
    LEFT_LOOP_BODY_UPPER: 'LeftLoopBodyUpper',
    LEFT_LOOP_HEAD: 'LeftLoopHead',
    LEFT_LOOP_BODY_LOWER: 'LeftLoopBodyLower',
    RIGHT_RAMP_GI: 'RightRampGI',
    SCOOP_LOWER_RIGHT_GI: 'ScoopLowerRightGI',
    LEFT_LOOP_ROLLOVER: 'LeftLoopRollover',
    LEFT_SAUCER: 'LeftSaucer',
    RIGHT_STANDUPS_UPPER: 'RightStandupsUpper',
    RIGHT_STANDUPS_MIDDLE: 'RightStandupsMiddle',
    RIGHT_STANDUPS_LOWER: 'RightStandupsLower',
    LEFT_STANDUPS_LOWSER: 'LeftStandupsLowser',
    LEFT_STANDUPS_MIDDLE: 'LeftStandupsMiddle',
    LEFT_STANDUPS_UPPER: 'LeftStandupsUpper',
    BOTTOM_ARCH_LEFT_LEFT: 'BottomArchLeftLeft',
    LEFT_INLANE_GI_RIGHT: 'LeftInlaneGIRight',
    LEFT_SLING_GI_UPPER: 'LeftSlingGIUpper',
    LEFT_LOOP_LOWER_GI: 'LeftLoopLowerGI',
    CAPTIVE_BALL_GI: 'CaptiveBallGI',
    SCOOP_LOWER_LEFT_GI: 'ScoopLowerLeftGI',
    SCOOP_UPPER_LEFT_GI: 'ScoopUpperLeftGI',
    JETS_TOP_GI: 'JetsTopGI',
    BOTTOM_ARCH_RIGHT_RIGHT: 'BottomArchRightRight',
    RIGHT_INLANE_GI_UPPER: 'RightInlaneGIUpper',
    RIGHT_SLING_GI_UPPER: 'RightSlingGIUpper',
    SHOOTER_RAMP_GI_LOWER: 'ShooterRampGILower',
    SHOOTER_RAMP_GI_MIDDLE: 'ShooterRampGIMiddle',
    RIGHT_STANDUPS_GI: 'RightStandupsGI',
    MIDDLE_JETS: 'MiddleJets',
    JETS_MIDDLE_GI: 'JetsMiddleGI',
    // Lamp matrix B
    SHIP_RIGHT_WING_UPPER: 'ShipRightWingUpper',
    SHIP_RIGHT_WING_LOWER: 'ShipRightWingLower',
    BONUS_X5: 'BonusX5',
    SHIP_TAIL_UPPER: 'ShipTailUpper',
    JEDI_SPIRIT: 'JediSpirit',
    RIGHT_HOTDOG_LEFT: 'RightHotdogLeft',
    JETS_ROLLOVER: 'JetsRollover',
    RIGHT_LASER_END: 'RightLaserEnd',
    SHIP_BODY_UPPER_RIGHT: 'ShipBodyUpperRight',
    SHIP_BODY_MIDDLE: 'ShipBodyMiddle',
    SHIP_BODY_LOWER: 'ShipBodyLower',
    BONUS_X4: 'BonusX4',
    JEDI_MASTER: 'JediMaster',
    FIRE_LASERS_RIGHT: 'FireLasersRight',
    RIGHT_SAUCER: 'RightSaucer',
    EXTRA_BALL: 'ExtraBall',
    SHIP_LEFT_WING_UPPER: 'ShipLeftWingUpper',
    SHIP_LEFT_WING_LOWER: 'ShipLeftWingLower',
    BONUS_X2: 'BonusX2',
    BONUS_X3: 'BonusX3',
    JEDI_YOUTH: 'JediYouth',
    LEFT_HOTDOG_RIGHT: 'LeftHotdogRight',
    SHOOTER: 'Shooter',
    BOTTOM_ARCH_RIGHT_LEFT: 'BottomArchRightLeft',
    SHOP_BODY_UPPER_LEFT: 'ShopBodyUpperLeft',
    SPOTLIGHT_RIGHT: 'SpotlightRight',
    FIRE_LASERS_LEFT: 'FireLasersLeft',
    JEDI_KNIGHT: 'JediKnight',
    SHOOT_AGAIN: 'ShootAgain',
    LEFT_FLIPPER: 'LeftFlipper',
    LEFT_LASER_END: 'LeftLaserEnd',
    LEFT_SAUCER_INSERT: 'LeftSaucerInsert',
    RIGHT_SAUCER_INSERT: 'RightSaucerInsert',
    SPOTLIGHT_LEFT: 'SpotlightLeft',
    LEFT_HOTDOG_LEFT: 'LeftHotdogLeft',
    RIGHT_HOTDOG_RIGHT: 'RightHotdogRight',
    RIGHT_FLIPPER: 'RightFlipper',
    SHIP_TAIL_LOWER: 'ShipTailLower',
    BOTTOM_ARCH_LEFT_RIGHT: 'BottomArchLeftRight',
    LEFT_INLANE_GI_LEFT: 'LeftInlaneGILeft',
    LEFT_SLING_GI_LOWER: 'LeftSlingGILower',
    LEFT_OUTLANE_GI: 'LeftOutlaneGI',
    LEFT_STANDUPS_GI: 'LeftStandupsGI',
    LEFT_LOOP_MIDDLE_GI: 'LeftLoopMiddleGI',
    UPPER_LEFT_CORNER_GI: 'UpperLeftCornerGI',
    LEFT_RAMP_GI: 'LeftRampGI',
    SCOOP_UPPER_RIGHT_GI: 'ScoopUpperRightGI',
    UPPER_RIGHT_CORNER_GI: 'UpperRightCornerGI',
    UPPER_JET: 'UpperJet',
    LOWER_JET: 'LowerJet',
    SHOOTER_RAMP_GI_UPPER: 'ShooterRampGIUpper',
    RIGHT_OUTLANE_GI: 'RightOutlaneGI',
    RIGHT_SLING_GI_LOWER: 'RightSlingGILower',
    RIGHT_INLANE_GI_RIGHT: 'RightInlaneGIRight'
};